#!/bin/bash
git clone https://gitlab.com/romanov73/example-jpa.git
cd example-jpa
./gradlew build
yum update
yum install postgresql
docker build -t sit -f dockerfile /home/albina
docker run -it --name=mycontainersit sit
